language: r

services:
    - docker

os:
    - linux

cache: packages

env:
    global:
        - RESULT_DIR=result-dir

git:
    depth: false
    submodules: false

before_install:
    # Git Config
    - git config --global user.name "ritboy"
    - git config --global user.email "ritboylei@gmail.com"

    # clone blog code
    - git clone https://${GITHUB_TOKEN}@github.com/ritboylei/travis-run-r-result.git ${RESULT_DIR}
    - cd ${RESULT_DIR}
    - echo "not start" > run_status
    - echo "not end" > excel_url.txt
    - echo "not end" > travis.log
    - git add .
    - git commit -m "not start to run"
    - git push
    - cd ..

    # docker
    - docker build -t ritboy/upload-to-alioss .
    - docker run --rm -v ${PWD}:/data ritboy/upload-to-alioss cp /uploadToAli /data
    - cat run_script.R | grep -Po "^library\(\K[^)]*" > install-library.txt
    - export EXCEL_FILE_NAME=`cat run_script.R | grep -Po "^write.xlsx\(\K[^)]*" | sed 's/ //g' | awk -F = '{print $2}' |sed 's/\"//g' | sed $'s/\'//g'`

install:
    - Rscript -e 'lib_list <- c(readLines("install-library.txt"));install.packages(lib_list)'

after_failure:
    - ls -alh
    - echo "failure" > ${RESULT_DIR}/run_status
    - echo "failure, please try again" > ${RESULT_DIR}/excel_url.txt
    - cd ${RESULT_DIR}
    - git add .
    - git commit -m "run failure"
    - git push

after_success:
    - ls
    - echo "success" > ${RESULT_DIR}/run_status
    - ./uploadToAli ${EXCEL_FILE_NAME} > ${RESULT_DIR}/excel_url.txt 2>&1
    - cd ${RESULT_DIR}
    - git add .
    - git commit -m "run success"
    - git push

script:
    - Rscript run_script.R > ${RESULT_DIR}/travis.log 2>&1
