install.packages("RISmed")
library(RISmed)

install.packages("lubridate")
library(lubridate)

search_topic <- c('SLE')
search_query <- EUtilsSummary(search_topic, retmax=500, mindate=2015, maxdate=year(ymd(Sys.Date())))
summary(search_query)
QueryId(search_query)
records<- EUtilsGet(search_query)
class(records)
pubmed_dataSLE<- data.frame('Title'=ArticleTitle(records),'Abstract'=AbstractText(records),'journal'=ISOAbbreviation(records),'ISSN'=ISSN(records))
head(pubmed_dataSLE,1)
pubmed_dataSLE$Abstract <- as.character(pubmed_dataSLE$Abstract)
pubmed_dataSLE$Abstract <- gsub(",", " ", pubmed_dataSLE$Abstract, fixed = TRUE)
str(pubmed_dataSLE)
View(pubmed_dataSLE)

install.packages("openxlsx")
library(openxlsx)
ISSN1<- read.xlsx('IF.xlsx',sheet=1)
View(ISSN1)
class(ISSN1)
str(ISSN1)
data1 <- merge(ISSN1,pubmed_dataSLE,by.x ='ISSN',by.y = 'ISSN')
View(data1)
write.xlsx(data1,file ='sm.xlsx')